version: '3'

services:
  nginx:
    build: ./nginx
    restart: always
    image: nginximage
    ports: 
      - "8088:80"
    depends_on:
      - node_service
    links:
      - node_service

  node_service: 
    build: ./api
    restart: always
    image: nodeimage
    ports: 
      - "3001:3000"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - db
    links:
      - db

  db:
    image: dbimage
    build: ./db/
    restart: always
    container_name: containerdb
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MARIADB_ROOT_PASSWORD: "password"
    volumes:
      - ./docker/db/init/init.sql:/docker-entrypoint-initdb.d/init.sql

