version: '3.4'

services:
  srv:
    image: srv
    build:
      context: challenge3/docker/api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
